# Generated by Django 2.0.4 on 2018-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('headshot', models.ImageField(default='livraria_app/static/livraria_app/image/authors/default_headshot.png', upload_to='livraria_app/static/livraria_app/image/authors')),
                ('biography', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.BigIntegerField(verbose_name='ISBN')),
                ('cover', models.ImageField(default='livraria_app/static/livraria_app/image/books/default_book_cover.jpg', upload_to='livraria_app/static/livraria_app/image/books', verbose_name='cover photo')),
                ('title', models.CharField(max_length=255)),
                ('pages', models.IntegerField(blank=True, verbose_name='Number of pages')),
                ('active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('authors', models.ManyToManyField(to='livraria_app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='livraria_app.Category'),
        ),
    ]
